name: Terraform Apply

on:
  push:
    branches: [ main ]

jobs:
  terraform-apply:
    runs-on: ubuntu-24.04
    env:
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      ROLE_NAME: ${{ vars.TERRAFORM_ROLE_NAME }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.1
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.TERRAFORM_ROLE_NAME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      working-directory: ./infrastructure/terraform/
      run: terraform init
    
    - name: Terraform Apply
      working-directory: ./infrastructure/terraform/
      run: terraform apply -auto-approve