name: Terraform Apply

on:
  push:
    branches: [ main ]

jobs:
  terraform-apply:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.1

    - name: Terraform Init
      working-directory: ./infrastructure/terraform/
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Terraform Apply
      working-directory: ./infrastructure/terraform/
      run: terraform apply -auto-approve