name: Terraform Plan

on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore:
      - main
    paths:
      - '**/*.tf'
      - '.github/workflows/terraform.yml'

jobs:
  terraform-plan:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.1

    - name: Terraform Format Check
      working-directory: ./infrastructure/terraform/
      run: |
        if ! terraform fmt -check -recursive -diff; then
          echo "Terraform files are not properly formatted. Please run 'terraform fmt' locally and commit the changes."
          exit 1
        fi

    - name: Terraform Init
      working-directory: ./infrastructure/terraform/
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Terraform Plan
      id: plan
      working-directory: ./infrastructure/terraform/
      run: terraform plan -no-color
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    