name: Terraform Plan

on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore:
      - main
    paths:
      - '**/*.tf'
      - '.github/workflows/terraform.yml'

jobs:
  terraform-plan:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    env:
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      ROLE_NAME: ${{ vars.TERRAFORM_ROLE_NAME }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.1
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.TERRAFORM_ROLE_NAME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Format Check
      working-directory: ./infrastructure/terraform/
      run: |
        if ! terraform fmt -check -recursive -diff; then
          echo "Terraform files are not properly formatted. Please run 'terraform fmt' locally and commit the changes."
          exit 1
        fi

    - name: Terraform Init
      working-directory: ./infrastructure/terraform/
      run: terraform init
    
    - name: Terraform Plan
      id: plan
      working-directory: ./infrastructure/terraform/
      run: terraform plan -no-color

    